version: '3'
services:
  mongo:
    container_name: cognum-database
    build: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
    networks:
      - local

  api:
    build: ./api
    container_name: cognum-api-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - local

  email-service:
    build: ./email-service
    container_name: cognum-email-service-app
    ports:
      - "3334:3333"
      - "3335:3333"
      - "3336:3333"
    depends_on:
      - mongo
    networks:
      - local

  lb-gateway:
    build: ./email-service/gateway
    container_name: cognum-lb-gateway-app
    ports:
      - "3333:80"
    depends_on:
      - email-service
    networks:
      - local

networks:
  local:
